baseURL = 'https://cutydina.github.io/'
languageCode = 'es-es'
title = 'CutyDina | Illustration & Game Dev'
theme = 'hugo-theme-bootstrap'

[params]
  defaultColor = 'dark'
  mainSections = ['blog', 'portfolio']
  cardHeight = '200px'
  breadcrumb = false

[menu]
  # Aquí replicamos el menú que tenías en la barra lateral de Blogger
  [[menu.main]]
    name = 'About'
    url = '/about'
    weight = 10
  [[menu.main]]
    name = 'Videogames'
    url = '/videogames'
    weight = 20
  [[menu.main]]
    name = 'Commissions'
    url = '/commissions'
    weight = 30
  [[menu.main]]
    name = 'Blog'
    url = '/blog'
    weight = 35

[params.comment]
  enable = false

[params.post]
  panel = false

[params.sidebar]
  archives = false
  taxonomiesToggleArchives = false

[params.archive]
  enable = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true