baseURL = 'https://cutydina.github.io/'
languageCode = 'es-es'
title = 'CutyDina | Illustration & Game Dev'
theme = 'hugo-theme-bootstrap'

[build]
  writeStats = true

[params]
  defaultColor = 'dark'
  dateFormat = '02/01/2006'
  postDate = true
  mainSections = ['blog', 'portfolio']
  cardHeight = '200px'
  breadcrumb = false
  toc = false
  tocPosition = 'content'

[menu]
  # Barra superior
  [[menu.main]]
    name = 'About'
    url = '/about'
    weight = 10
  [[menu.main]]
    name = 'Videogames'
    url = '/videogames'
    weight = 20
  [[menu.main]]
    name = 'Commissions'
    url = '/commissions'
    weight = 30

  # Barra lateral izquierda
  [[menu.sidebar]]
    name = 'Commissions'
    url = '/portfolio/commissions'
    weight = 10
  [[menu.sidebar]]
    name = 'Personal Work'
    url = '/portfolio/personalwork'
    weight = 20
  [[menu.sidebar]]
    name = 'Projects'
    url = '/portfolio/projects'
    weight = 30
  [[menu.sidebar]]
    name = 'Blog'
    url = '/blog'
    weight = 40

[params.comment]
  enable = false

[params.post]
  panel = false

[params.sidebar]
  taxonomiesToggle = false
  archives = false
  taxonomiesToggleArchives = false
  postsToggle = false

[params.archive]
  enable = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true