baseURL = 'https://cutydina.github.io/'
languageCode = 'en-us'
title = 'CutyDina'
description = "Illustration, Animation, Children's Books, Videogames, Web Design, Comics and more."
theme = 'hugo-theme-bootstrap'
author = "Geraldina Sierra"
keywords = "cutydina, geraldina sierra, cuty dina, illustration, 2danimation, commissions"

[params.author]
  name = "Geraldina Sierra"
  bio = "2D Illustrator & Animator"
  avatar = "images/profile.webp"


[params.social]
  discord = "TpTmfBb2bC"
  linkedin = "geraldinasierra"
  facebook = "geraldinasierra"
  github = "cutydina"
  instagram = "cutydina"
  paypal = "geraldinasierra"
  pinterest = "geraldinasierra"
  reddit = "CutyDina"
  telegram = "cutydina"
  tiktok = "cutydina"
  website = "https://cutydina.com"
  youtube = "CutyDina"
  email = "info@cutydina.com"

googleAnalytics = 'G-5V76N0CTHP'

[params.og]
  image = "images/VGenCommissions.webp"
  locale = "en_US"

[build]
  writeStats = true

[params]
  color = 'light'
  dateFormat = '02/01/2006'
  postDate = true
  mainSections = ['blog', 'portfolio']
  cardHeight = '200px'
  breadcrumb = false
  toc = false
  tocPosition = 'content'
  copyright = "© 2026 Geraldina Sierra. CutyDina® - All rights reserved."
  rss = true
  favicon = "images/favicon.svg"
  googleSiteVerification = "2f512d19a85c2175d8570896032c92a7"

[menu]
  # Barra superior
  [[menu.main]]
    name = 'About'
    url = '/about'
    weight = 10
  [[menu.main]]
    name = 'Videogames'
    url = '/videogames'
    weight = 20
  [[menu.main]]
    name = 'Commissioned Work'
    url = '/commissions'
    weight = 30

  # Barra lateral izquierda
  [[menu.sidebar]]
    name = 'Projects'
    url = '/portfolio/projects'
    weight = 10
  [[menu.sidebar]]
    name = 'Personal Work'
    url = '/portfolio/personalwork'
    weight = 20
  [[menu.sidebar]]
    name = 'FanArts'
    url = '/portfolio/fanart'
    weight = 30
  [[menu.sidebar]]
    name = 'Commissioned Work'
    url = '/portfolio/commissionedwork'
    weight = 40
  [[menu.sidebar]]
    name = 'Blog'
    url = '/blog'
    weight = 50

[params.comment]
  enable = false

[params.post]
  panel = false

[params.sidebar]
  taxonomiesToggle = false
  archives = false
  taxonomiesToggleArchives = false
  postsToggle = false

[params.archive]
  enable = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true