const options = {
  toolbar: {
    zoomIn: true,
    zoomOut: true,
    oneToOne: false,
    reset: false,
    prev: true,
    play: false,
    next: true,
    enter: false,
    exit: false,
    rotateLeft: false,
    rotateRight: false,
    flipHorizontal: false,
    flipVertical: false,
  },
  navbar: false,
  title: false,
  tooltip: true,
  transition: true,
  fullscreen: true,
  keyboard: true,
  loop: true,
  backdrop: true,
  loading: true,
  discrete: true,
  container: null,
  inherited: true,
  focus: true,
  movable: true,
  zoomable: true,
  rotatable: false,
  scalable: false,
  toggleOnDblclick: true,
  ready: null,
  show: null,
  shown: null,
  hide: null,
  hidden: null,
  view: null,
  viewed: null,
  zoom: null,
  zoomed: null,
};

export default options;
